# Server Port
server.port=${PORT:8080}

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://root:FhFcMAPHHPdfTBrMEVRgkSghsmrKhjgo@trolley.proxy.rlwy.net:24316/railway
spring.datasource.username=${root}
spring.datasource.password=${FhFcMAPHHPdfTBrMEVRgkSghsmrKhjgo}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MySQL Dialect (important)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect